version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    volumes:
      - static_volume:/home/flasker/web/static/uploads
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 app:app
    expose:
      - 5000
    volumes:
      - static_volume:/home/flasker/web/static/uploads
    env_file:
      - ./.env.prod

volumes:
  static_volume:
