version: '3.8'

services:
  nginx:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ShareXScreenShotServer.rule=Host(`example.com`)"
      - "traefik.http.routers.ShareXScreenShotServer.entrypoints=websecure"
      - "traefik.http.routers.ShareXScreenShotServer.tls.certresolver=letsencrypt"
    build: ./nginx
    expose:
      - 80
    volumes:
      - static_volume:/home/flasker/web/static/uploads
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 app:app
    expose:
      - 5000
    volumes:
      - static_volume:/home/flasker/web/static/uploads
    env_file:
      - ./.env.prod

volumes:
  static_volume:

networks:
  default:
    external:
      name: traefik
